name: CrystalDelivery
version: '1.0-SNAPSHOT'
main: earth.crystalmc.crystalDelivery.CrystalDelivery
api-version: '1.20'
author: myoko_1110
depend:
  - Vault
commands:
  delivery:
    permissions:
      crystaldelivery.*:
        description: CrystalDelivery のコマンドを使用するすべての権利を与えます
        children:
          crystaldelivery.delivery: true
          crystaldelivery.send: true
          crystaldelivery.post: true
          crystaldelivery.redelivery: true
          crystaldelivery.reload: true
      crystaldelivery.send:
        default: true
      crystaldelivery.post:
        default: true
      crystaldelivery.redelivery:
        default: true
      crystaldelivery.reload:
        default: false
